require("dotenv").config();
const nodemailer = require("nodemailer");
const transport = nodemailer.createTransport({
  service: "Gmail",
  auth: {
    user: process.env.email,
    pass: process.env.password,
  },
});
const sendEmail = (to, subject, message) => {
  const mailOptions = {
    from: process.env.email,
    to,
    subject,
    html: message,
  };
  transport.sendMail(mailOptions, (error) => {
    if (error) {
      console.log(error);
    } else {
      console.log("success");
    }
  });
};

const generateMessage = (name, email, password, role) => {
  const message = `Hello ${name},
              <br/><br/>
              ${name} your <strong>LegiView</strong> account has created with <strong>${role}</strong> Role please find Login credientials below
              <br/>
              <small>email: ${email} <br> password: ${password}</small><br><br>
              <small>click here to login </small>
              <small><a href="${process.env.ORIGIN}">${process.env.ORIGIN}</a></small><br/><br/>
              <small>This email is auto-generated by <strong>Legiview</strong></small>.<br/>
              <small><i>Please do not reply to this message</i></small><br/><br/><br/>`;
  return message;
};
module.exports = { sendEmail, generateMessage };
